dist: bionic

language: generic

branches:
  only:
  - master

services:
  - docker

before_install:
  - docker info
  - docker login --username=${DOCKER_USER} --password=${DOCKER_PASSWORD}

install:
  - docker pull centos:centos6

script:
  - docker build -t worksg/python-36-centos6 .
  - docker images
  - docker push worksg/python-36-centos6